baseURL = "https://joshbergman.dev"
title = "joshbergman.dev"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "joshbergman.dev"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "My name is Josh Bergman." 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = ""

    # The name to display in the copyright section in the footer
    copyrightname = "jb"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks
    #facebook = "https://facebook.com" 
    #twitter = "https://twitter.com" 
    linkedin = "https://www.linkedin.com/in/josh-bergman-5104b988"
    github = "https://github.com/b3rgman/"
    gitlab = "https://gitlab.com/b3rgman"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 2.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = true

[params.copyright]
    name = "jb"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    #prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    #suffix = "Example site"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about"
    name = "About"      
    url = "/about/"    
    weight = 10       

  [[menu.main]] 
    identifier = "posts" 
    name = "posts"
    url = "/posts/"     
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = true
    simple = true

  [privacy.twitter]
    disabled = true
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = true
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
