---
label: Default
hide_body: false
fields:
- type: datetime
  name: date
  label: date
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: text
  name: info
  label: info
- type: text
  name: slug
  label: slug
- type: list
  name: authors
  label: authors
- type: list
  name: tags
  label: tags
- type: list
  name: categories
  label: categories
- type: text
  name: externalLink
  label: externalLink
- type: list
  name: series
  label: series
pages:
- content/markdownpage.md
- content/the-matrix.md
